### ISSUE TITLE
Fails to compile when default locale isn’t "en"

### ISSUE THREAD

**Issue by jayjun** [kipcole9/cldr#17]
### Steps to Replicate

1. Create a new Mix project and add Cldr as a dependency.

```elixir
def deps do
  [{:ex_cldr, "0.4.1"}]
end
```
2. Set `default_locale` to `en-SG`.
```elixir
config :ex_cldr,
  default_locale: "en-SG"
```

3. Run `mix do deps.get, compile`.

### Stacktrace

```
==> ex_cldr
Compiling 6 files (.erl)
Compiling 40 files (.ex)
Generating Cldr for 3 locales ["en-SG", "root"] with default locale "en-SG"

== Compilation error on file lib/cldr.ex ==
** (UndefinedFunctionError) function Cldr.all_locales/0 is undefined (module Cldr is not available)
    Cldr.all_locales()
    lib/cldr/install.ex:62: Cldr.Install.install_locale/2
    lib/cldr/config.ex:398: Cldr.Config.get_locale/1
    lib/cldr.ex:189: anonymous fn/1 in :elixir_compiler_13.__MODULE__/1
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    lib/cldr.ex:188: (module)
```

### Reason

Under these circumstances, compile-time code in the `Cldr` module ends up calling itself with `Cldr.all_locales/0`, which doesn’t exist yet.

**Comment by kipcole9** [comment]
Fixed in [release 0.4.2](https://hex.pm/packages/ex_cldr).  Thanks for the bug report.
