### ISSUE TITLE
Compiler failing under elixir 1.7-rc

### ISSUE THREAD

**Issue by LostKobrakai** [kipcole9/cldr#69]
Details are already here: https://elixirforum.com/t/elixir-v1-7-0-rc-0-released/15133/20?u=lostkobrakai

```
could not compile dependency :ex_cldr_dates_times, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_cldr_dates_times", update it with "mix deps.update ex_cldr_dates_times" or clean it with "mix deps.cleanex_cldr_dates_times"
** (FunctionClauseError) no function clause matching in Mix.Dep.loaded/1

    The following arguments were given to Mix.Dep.loaded/1:

        # 1
        [env: :prod]

    Attempted function clauses (showing 1 out of 1):

        def loaded([])

    (mix) lib/mix/dep.ex:156: Mix.Dep.loaded/1
    lib/mix/tasks/compile.cldr.ex:86: Mix.Tasks.Compile.Cldr.compile_cldr_files/0
    lib/mix/tasks/compile.cldr.ex:67: Mix.Tasks.Compile.Cldr.run/1
    (mix) lib/mix/task.ex:316: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1
```

`Mix.Dep.loaded` is deprecated and to be removed in 1.8

**Comment by kipcole9** [comment]
Yet another reason to work faster on Cldr version 2 so. Can get rid of this ‘compiler’.  I do test on 1.7 but I am a couple of weeks behind on commits so clearly I need t get onto the RC now.

Will dive into this today and see if I can resolve another way.  Thanks for the issue.
